server:
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OneSpring?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
    group:
      dev:
        - dev
        - local
      prod:
        - prod
        - prod-local
  # flyway 配置
  flyway:
    enabled: true
    encoding: utf-8
    # sql文件存放位置
    locations: classpath:db/migration
    # 版本记录表格
    table: flyway_schemas_version
    baseline-on-migrate: false
    validate-on-migrate: true
    ignore-missing-migrations: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true